language: rust
cache: cargo
rust:
  - stable
  - 1.20.0
  - beta
  - nightly

script:
  - export PATH=$PATH:~/.cargo/bin
  - make all

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TEST_THREADS=1
  matrix:
    -
    - RELEASE=true

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
