[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]
options = ["--edition", "2024"]

[formatter.toml]
command = "taplo"
includes = ["*.toml"]
options = ["format"]
