[package]
name = "dotr"
version = "0.4.0"
edition = "2024"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Very simple dotfile manager"
documentation = "https://docs.rs/dotr/"
homepage = "https://github.com/dpc/dotr"
keywords = ["dot", "dotfile", "rc"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/dpc/dotr"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
walkdir = "2"

[dev-dependencies]
tempfile = "3"

[lints.rust]
missing_docs = "warn"
unsafe_code = "deny"
unused = { level = "deny", priority = -1 }

[lints.clippy]
dbg_macro = "deny"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
todo = "deny"

[profile.ci]
debug = "line-tables-only"
incremental = false
inherits = "dev"
lto = "off"

[profile.release]
strip = true
